### ISSUE TITLE
GUI Doesn't load

### ISSUE THREAD

**Issue by jfy133** [Integrative-Transcriptomics/DamageProfiler#38]
I just saw on the README you also have a GUI version.

I just tried loading it both with the conda version and github repo JAR release, but I get the following error

```
(damageprofiler) fellows@shh.mpg.de@dat4903339:~/Downloads$ java -jar DamageProfiler-0.4.9.jar 
0.4.9
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: javafx/application/Application
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at RunDamageProfiler.lambda$main$0(RunDamageProfiler.java:31)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 11 more
```

I am using openJDK:

```
(damageprofiler) fellows@shh.mpg.de@dat4903339:~/Downloads$ java -version
openjdk version "11.0.1-internal" 2018-10-16
OpenJDK Runtime Environment (build 11.0.1-internal+0-adhoc..src)
OpenJDK 64-Bit Server VM (build 11.0.1-internal+0-adhoc..src, mixed mode)
```

On Ubuntu 

```
(damageprofiler) fellows@shh.mpg.de@dat4903339:~/Downloads$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

**Comment by JudithNeukamm** [comment]
Jep, it's not adapted to Java > 9 yet, but it's on the todo list. It only runs with java8 at the moment.

**Comment by JudithNeukamm** [comment]
Can you please try it again with the new version 0.5.0? 
I tested it successfully under Ubuntu 18.04 LTS and Java11.

**Comment by jfy133** [comment]
![image](https://user-images.githubusercontent.com/17950287/89330461-8ef0c580-d690-11ea-882c-100350cd0fe0.png)

(from Downloading JAR from here, as looks like bioconda not updated yet)
