### ISSUE TITLE
Offer build with older version of Java?

### ISSUE THREAD

**Issue by jfy133** [Integrative-Transcriptomics/DamageProfiler#43]
Hi @JudithNeukamm ,

I just tried bumping the DamageProfile version in nf-core/eager to 0.5.0, but when I tried doing it failed with an issue saying 'the JAR was built with a later version of jdk which is not compatible with the Java in the environment'. conda currently uses Java 8, and therefore all other tools assume this is being used (by default). While I could update the conda recipe to specify it needs >=14, this will make it incompatible with all other tools in nf-core/eager.

Would it possible to either downgrade the build to java 8 (which I assume was working fine before, unless v0.5.0 have some big changes), or could you somehow offer two builds (one for 8, and one for 14)?

I understand all the tools should be upgrade to latest version, but you know academia and software maintenance... 

Let me know what you think.

Cheers,

**Comment by JudithNeukamm** [comment]
Hi, 
yes, I also encountered already this issue with the versions....I'll upload two builds for the current version (for java8 and java11 and higher).
Cheers

**Comment by jfy133** [comment]
Awesome thank you :D, let me know and I can do a re-build of the bioconda package. Much appreciated!

**Comment by JudithNeukamm** [comment]
I uploaded the new jar to the existing release of Version 0.5.0
Does this work for you or do you need it as a separate release?

**Comment by jfy133** [comment]
Will test now! I don't think will need a separate release, just need to
bump the conda build with the changes

**Comment by jfy133** [comment]
Sorry, got side-tracked, will test either tonight or tomorrow morning. Will get back to you ASAP

**Comment by JudithNeukamm** [comment]
No problem :)

**Comment by jfy133** [comment]
Ok, finally got around to it.

```
(damageprofiler) sos@dat4903339:08:49:JK2782:(doc-improvements)$ java -jar DamageProfiler-0.5.0-java8.jar 
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: javafx/application/Application
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at RunDamageProfiler.lambda$main$0(RunDamageProfiler.java:21)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 14 more
(damageprofiler) sos@dat4903339:08:49:JK2782:(doc-improvements)$ java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (Zulu 8.48.0.53-CA-linux64) (build 1.8.0_265-b11)
OpenJDK 64-Bit Server VM (Zulu 8.48.0.53-CA-linux64) (build 25.265-b11, mixed mode)
```

Is this to be expected? Should JavaFX be built within the JAR or is it a dependency?

**Comment by JudithNeukamm** [comment]
You need to install JavaFX separately:
sudo apt install openjfx

**Comment by jfy133** [comment]
Hmm, ok this will be a problem then for nf-core/eagereager, AFAIK (and google tells me) JavaFX is not available any older than version 11 on conda... we might have to try bumping to Java11 @apeltzer? At least the latest version of MALT I set as Java >= 11? 

Sorry, @JudithNeukamm I can't test the Java8 build unfortunately as my laptop is running Java version 11, and if the JavaFX version for Java8 doesn't exist on conda then I'm stuck :(

**Comment by jfy133** [comment]
After discussion via email with @JudithNeukamm decided it's not worth investing more time into this just for bioconda (where the JavaFX version is not yet avaliable, and might not ever be as Java8 is so old).
