### ISSUE TITLE
java.lang.OutOfMemoryError: Requested array size exceeds VM limit

### ISSUE THREAD

**Issue by ChristopherBarrington** [Integrative-Transcriptomics/DamageProfiler#57]
damageprofiler produces the following error with two particularly big datasets. I run damageprofiler via the nf-core/eager 2.3.3 pipeline so I am limited to the changes I can make.

```
DamageProfiler v0.4.9
Exception in thread "main" java.lang.OutOfMemoryError: Requested array size exceeds VM limit
        at org.apache.commons.math3.util.ResizableDoubleArray.expand(ResizableDoubleArray.java:697)
        at org.apache.commons.math3.util.ResizableDoubleArray.addElement(ResizableDoubleArray.java:442)
        at org.apache.commons.math3.stat.descriptive.DescriptiveStatistics.addValue(DescriptiveStatistics.java:171)
        at IO.OutputGenerator.computeSummaryMetrics(OutputGenerator.java:542)
        at calculations.StartCalculations.generateOutput(StartCalculations.java:357)
        at calculations.StartCalculations.start(StartCalculations.java:302)
        at RunDamageProfiler.main(RunDamageProfiler.java:37)
```

After some desperate googling I tried changing the `Xmx` option to use more memory but I think that was never going to work given the error is about a VM limit rather than memory specifically.

```
damageprofiler -Xmx1300g -i rmdup.bam -r genome.fa -l 100 -t 15 -o . -yaxis_damageplot 0.30
```

The input bam files are 44 or 53 GB with 1,329,979,427 and 1,516,157,394 records (which I guess are being read into an array?!) according to a sum of the bai. My (naive) understanding of java arrays is that they should be able to accommodate this many elements with a 64-bit JVM but I don't know how the arrays are used in damageprofiler.

the singularity image for eager 2.3.3 uses:

```
> java -version
openjdk version "1.8.0_144"
OpenJDK Runtime Environment (Zulu 8.23.0.3-linux64) (build 1.8.0_144-b01)
OpenJDK 64-Bit Server VM (Zulu 8.23.0.3-linux64) (build 25.144-b01, mixed mode)
> damageprofiler --version
DamageProfiler v0.4.9
```

Is there anything I can try to get these datasets processed? I would prefer to keep the analysis within the nf-core/eager pipeline but may be able to run independently with updated java if that could be a solution. If you think this is more a problem with the eager pipeline I can ask there.

Thank you for your time.

**Comment by apeltzer** [comment]
I would rather ask this on the nf-core/eager pipeline as you will get more help there. Increasing the limits is one thing we could do, also it would be potenitally possible to subsample the BAM if it's too large & run it on that subsampled filed. The patterns should not really change too much and provide you with a good trend.

**Comment by ChristopherBarrington** [comment]
So if I go into the cextflow work directory for the affected processes, make a subsampled bam file (say 50%?), remove the parts in `.commmand.run` that symlink the bam file then resubmit the job. That should run damageprofiler with the same parameters but on a subsample of the bam. Is that what you suggest?

I have tried many memory options now and I don't think it helps, I'm more convinced its a problem caused by the number of reads in the bam so subsampling makes sense.
