### ISSUE TITLE
How to run in Computing Cluster? 

### ISSUE THREAD

**Issue by sultandromeda** [Integrative-Transcriptomics/DamageProfiler#60]
Hi, Thanks for a cool tool

I am struggling to use it in computing clusters
I uploaded tar.gz and opened it with the following command:
> tar -xzvf v1.1.tar.gz

I tried to use via: 
> java -Xmx8G -jar /project/lab/sultandromeda/DamageProfiler/DamageProfiler-1.1/jars/DamageProfiler-1.0-java8.jar 

and it showed this error:
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: javafx/application/Application
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at RunDamageProfiler.lambda$main$0(RunDamageProfiler.java:23)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 14 more
        
       
This is my first time using this tool, and I quite do not get it how to run. I appreciate your help

**Comment by JudithNeukamm** [comment]
Hello!
It looks like the JavaFX is missing. Have to tried to install it alongside Java? If you are using Ubuntu, you can easily use this command for installing: 

`sudo apt-get install openjfx`

Let me know if this is not working.

**Comment by sultandromeda** [comment]
Hi Judith,

I used module load java/17, and it worked. Thank you a lot!
